// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MultiProjectTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidProjectImportToolsPackageString = "0d25ea8f-216b-4893-b5b1-61b29f7f4d1a";
        public const string guidImageCatelogString = "d79d376d-8c80-4b54-83fc-dd1879df4c4d";
        public const string guidSolutionCmdSetString = "41d4d218-2a81-4e87-b97f-27a3711f6bf8";
        public const string guidProjectCmdSetString = "b7c7912a-63aa-47ae-a2bc-08447aaf625d";
        public static Guid guidProjectImportToolsPackage = new Guid(guidProjectImportToolsPackageString);
        public static Guid guidImageCatelog = new Guid(guidImageCatelogString);
        public static Guid guidSolutionCmdSet = new Guid(guidSolutionCmdSetString);
        public static Guid guidProjectCmdSet = new Guid(guidProjectCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddProjects = 0x0001;
        public const int ReferenceWarning = 0x0002;
        public const int Reference = 0x0003;
        public const int ModuleFile = 0x0004;
        public const int SolutionMenu = 0x1000;
        public const int SolutionMenuGroup = 0x0100;
        public const int cmdAddExistingProjects = 0x0001;
        public const int cmdCreateProjectReferences = 0x0002;
        public const int cmdLoadReferenceFiles = 0x0003;
        public const int ProjectMenuGroup = 0x0100;
        public const int cmdResolveReferences = 0x0001;
    }
}
