// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MultiProjectTools
{
    static class Vsix
    {
        public const string Id = "c2187b09-a91f-4f43-803e-223a51340f85";
        public const string Name = "Project Import Tools";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Matthew Hartshorn";
        public const string Tags = "Project, Import, Solution Explorer, References, Resolve References, Upgrade Project, Remove Source Control, Add Existing Projects";
    }
}
